feat(ansible): update and restructure roles
- Updated .gitignore file
- Added new ansible.cfg
- Modified bootstrap.yml
- Deleted obsolete role files for conda, docker, go, k3s, and rust
- Added new tasks for miniforge3 and nodejs roles
- Modified tasks for neovim, stow, and wsl_clipboard_support
- Updated install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,22 @@
 #!/usr/bin/env bash
 
-cd ansible
-ansible-playbook bootstrap.yml --ask-become-pass
+set -e # Exit immediately if a command exits with a non-zero status
+
+# Ensure Ansible is installed
+if ! command -v ansible >/dev/null 2>&1; then
+  echo "Ansible is not installed. Installing..."
+  echo "Checking if pipx is installed..."
+  # install pipx inf not installed
+  if ! command -v pipx >/dev/null 2>&1; then
+    echo "pipx is not installed. Installing..."
+    python3 -m pip install --user pipx
+  else
+    echo "pipx is installed."
+  fi
+  python3 -m pipx install ansible
+  python3 -m pipx ensurepath
+fi
+
+# Run Ansible bootstrap playbook
+echo "Running Ansible playbook..."
+ANSIBLE_CONFIG="./ansbile/ansible.cfg" ansible-playbook "./ansible/bootstrap.yml"
